// Create Sample Twitter Data
// This script creates a small sample dataset for development

// Clear existing data
MATCH (n) DETACH DELETE n;

// Create Users
CREATE (u1:User {id: '1', username: 'john_doe', name: 'John Doe', followers: 1500, following: 300})
CREATE (u2:User {id: '2', username: 'jane_smith', name: 'Jane Smith', followers: 3200, following: 450})
CREATE (u3:User {id: '3', username: 'tech_guru', name: 'Tech Guru', followers: 15000, following: 200})
CREATE (u4:User {id: '4', username: 'data_scientist', name: 'Data Scientist', followers: 8500, following: 600})
CREATE (u5:User {id: '5', username: 'neo4j_fan', name: 'Neo4j Fan', followers: 2100, following: 350})
CREATE (u6:User {id: '6', username: 'graphdb_expert', name: 'Graph DB Expert', followers: 5600, following: 280})
CREATE (u7:User {id: '7', username: 'ai_researcher', name: 'AI Researcher', followers: 12000, following: 150})
CREATE (u8:User {id: '8', username: 'web_developer', name: 'Web Developer', followers: 4200, following: 520})
CREATE (u9:User {id: '9', username: 'cloud_architect', name: 'Cloud Architect', followers: 7800, following: 390})
CREATE (u10:User {id: '10', username: 'startup_founder', name: 'Startup Founder', followers: 9500, following: 420})

// Create Hashtags
CREATE (h1:Hashtag {name: 'neo4j'})
CREATE (h2:Hashtag {name: 'graphdatabase'})
CREATE (h3:Hashtag {name: 'datascience'})
CREATE (h4:Hashtag {name: 'machinelearning'})
CREATE (h5:Hashtag {name: 'ai'})
CREATE (h6:Hashtag {name: 'javascript'})
CREATE (h7:Hashtag {name: 'typescript'})
CREATE (h8:Hashtag {name: 'react'})
CREATE (h9:Hashtag {name: 'cloud'})
CREATE (h10:Hashtag {name: 'devops'})

// Create Tweets
CREATE (t1:Tweet {id: '101', text: 'Just discovered Neo4j and I am amazed by graph databases! #neo4j #graphdatabase', createdAt: datetime('2024-01-15T10:30:00')})
CREATE (t2:Tweet {id: '102', text: 'Working on a new machine learning project using graph algorithms #datascience #machinelearning #neo4j', createdAt: datetime('2024-01-16T14:20:00')})
CREATE (t3:Tweet {id: '103', text: 'TypeScript + React = Perfect combination for modern web development #typescript #react #javascript', createdAt: datetime('2024-01-17T09:15:00')})
CREATE (t4:Tweet {id: '104', text: 'Graph databases are the future of connected data #neo4j #graphdatabase', createdAt: datetime('2024-01-18T16:45:00')})
CREATE (t5:Tweet {id: '105', text: 'Building a recommendation engine with Neo4j, incredible performance! #neo4j #datascience', createdAt: datetime('2024-01-19T11:00:00')})
CREATE (t6:Tweet {id: '106', text: 'AI and graph databases working together for better insights #ai #neo4j #machinelearning', createdAt: datetime('2024-01-20T13:30:00')})
CREATE (t7:Tweet {id: '107', text: 'Deploying Neo4j on cloud infrastructure #cloud #devops #neo4j', createdAt: datetime('2024-01-21T10:00:00')})
CREATE (t8:Tweet {id: '108', text: 'React hooks make state management so much easier #react #javascript', createdAt: datetime('2024-01-22T15:20:00')})
CREATE (t9:Tweet {id: '109', text: 'Graph algorithms for fraud detection in financial systems #neo4j #datascience', createdAt: datetime('2024-01-23T09:45:00')})
CREATE (t10:Tweet {id: '110', text: 'Love how Neo4j handles complex relationships #neo4j #graphdatabase', createdAt: datetime('2024-01-24T14:10:00')})
CREATE (t11:Tweet {id: '111', text: 'Building a knowledge graph for our AI platform #ai #neo4j', createdAt: datetime('2024-01-25T11:30:00')})
CREATE (t12:Tweet {id: '112', text: 'TypeScript strict mode catches so many bugs early #typescript #javascript', createdAt: datetime('2024-01-26T16:00:00')})
CREATE (t13:Tweet {id: '113', text: 'Microservices architecture with graph database backend #cloud #neo4j #devops', createdAt: datetime('2024-01-27T10:45:00')})
CREATE (t14:Tweet {id: '114', text: 'Data science workflows powered by graph analytics #datascience #neo4j', createdAt: datetime('2024-01-28T13:15:00')})
CREATE (t15:Tweet {id: '115', text: 'Next.js + Neo4j = Amazing tech stack #react #javascript #neo4j', createdAt: datetime('2024-01-29T09:30:00')})

// Create POSTED relationships (User -> Tweet)
MATCH (u:User {id: '1'}), (t:Tweet {id: '101'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '3'}), (t:Tweet {id: '102'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '8'}), (t:Tweet {id: '103'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '5'}), (t:Tweet {id: '104'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '4'}), (t:Tweet {id: '105'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '7'}), (t:Tweet {id: '106'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '9'}), (t:Tweet {id: '107'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '8'}), (t:Tweet {id: '108'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '6'}), (t:Tweet {id: '109'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '5'}), (t:Tweet {id: '110'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '7'}), (t:Tweet {id: '111'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '8'}), (t:Tweet {id: '112'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '9'}), (t:Tweet {id: '113'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '4'}), (t:Tweet {id: '114'}) CREATE (u)-[:POSTED]->(t)
MATCH (u:User {id: '3'}), (t:Tweet {id: '115'}) CREATE (u)-[:POSTED]->(t)

// Create TAGGED relationships (Tweet -> Hashtag)
MATCH (t:Tweet {id: '101'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '101'}), (h:Hashtag {name: 'graphdatabase'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '102'}), (h:Hashtag {name: 'datascience'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '102'}), (h:Hashtag {name: 'machinelearning'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '102'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '103'}), (h:Hashtag {name: 'typescript'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '103'}), (h:Hashtag {name: 'react'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '103'}), (h:Hashtag {name: 'javascript'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '104'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '104'}), (h:Hashtag {name: 'graphdatabase'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '105'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '105'}), (h:Hashtag {name: 'datascience'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '106'}), (h:Hashtag {name: 'ai'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '106'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '106'}), (h:Hashtag {name: 'machinelearning'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '107'}), (h:Hashtag {name: 'cloud'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '107'}), (h:Hashtag {name: 'devops'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '107'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '108'}), (h:Hashtag {name: 'react'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '108'}), (h:Hashtag {name: 'javascript'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '109'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '109'}), (h:Hashtag {name: 'datascience'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '110'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '110'}), (h:Hashtag {name: 'graphdatabase'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '111'}), (h:Hashtag {name: 'ai'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '111'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '112'}), (h:Hashtag {name: 'typescript'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '112'}), (h:Hashtag {name: 'javascript'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '113'}), (h:Hashtag {name: 'cloud'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '113'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '113'}), (h:Hashtag {name: 'devops'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '114'}), (h:Hashtag {name: 'datascience'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '114'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '115'}), (h:Hashtag {name: 'react'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '115'}), (h:Hashtag {name: 'javascript'}) CREATE (t)-[:TAGGED]->(h)
MATCH (t:Tweet {id: '115'}), (h:Hashtag {name: 'neo4j'}) CREATE (t)-[:TAGGED]->(h)

// Create MENTIONS relationships (Tweet -> User)
MATCH (t:Tweet {id: '102'}), (u:User {id: '5'}) CREATE (t)-[:MENTIONS]->(u)
MATCH (t:Tweet {id: '103'}), (u:User {id: '3'}) CREATE (t)-[:MENTIONS]->(u)
MATCH (t:Tweet {id: '105'}), (u:User {id: '3'}) CREATE (t)-[:MENTIONS]->(u)
MATCH (t:Tweet {id: '106'}), (u:User {id: '4'}) CREATE (t)-[:MENTIONS]->(u)
MATCH (t:Tweet {id: '111'}), (u:User {id: '3'}) CREATE (t)-[:MENTIONS]->(u)
MATCH (t:Tweet {id: '115'}), (u:User {id: '8'}) CREATE (t)-[:MENTIONS]->(u)

// Create FOLLOWS relationships (User -> User)
MATCH (u1:User {id: '1'}), (u2:User {id: '3'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '1'}), (u2:User {id: '5'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '2'}), (u2:User {id: '3'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '2'}), (u2:User {id: '7'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '3'}), (u2:User {id: '4'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '4'}), (u2:User {id: '3'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '4'}), (u2:User {id: '7'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '5'}), (u2:User {id: '3'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '5'}), (u2:User {id: '6'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '6'}), (u2:User {id: '3'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '6'}), (u2:User {id: '5'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '7'}), (u2:User {id: '4'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '8'}), (u2:User {id: '3'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '9'}), (u2:User {id: '3'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '9'}), (u2:User {id: '10'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '10'}), (u2:User {id: '7'}) CREATE (u1)-[:FOLLOWS]->(u2)
MATCH (u1:User {id: '10'}), (u2:User {id: '9'}) CREATE (u1)-[:FOLLOWS]->(u2)

// Note: Indexes should be created separately in Neo4j Browser or via separate commands
// For Neo4j 5.x, use:
// CREATE INDEX user_id IF NOT EXISTS FOR (u:User) ON (u.id)
// CREATE INDEX user_username IF NOT EXISTS FOR (u:User) ON (u.username)
// CREATE INDEX tweet_id IF NOT EXISTS FOR (t:Tweet) ON (t.id)
// CREATE INDEX hashtag_name IF NOT EXISTS FOR (h:Hashtag) ON (h.name)

